name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run tests
        run: go test -cover ./...

      - name: Force Failure
        run: go version
  
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install staticcheck
        run: |
          echo "${GOPATH}/bin" >> $GITHUB_PATH
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Style
        run: test -z $(go fmt ./...)